// <auto-generated />
using System;
using Eshop.Discount.Grpc.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eshop.Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    partial class DiscountContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Eshop.Discount.Grpc.Domain.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            Amount = 50.0m,
                            ProductId = new Guid("9e9f7ac4-2768-4e6c-af21-226f51faa511")
                        },
                        new
                        {
                            CouponId = 2,
                            Amount = 55.0m,
                            ProductId = new Guid("27cbb917-1c47-443e-bbea-a868f0d99da1")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
