services:
  eshop.catalog.database:
    image: postgres

  eshop.catalog.api:
    image: ${DOCKER_REGISTRY-}eshopcatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Eshop.Catalog.Api/Dockerfile
  
  eshop.basket.database:
    image: postgres
  
  eshop.basket.cache:
    image: redis

  eshop.basket.api:
    image: ${DOCKER_REGISTRY-}eshopbasketapi
    build:
      context: .
      dockerfile: Services/Basket/Eshop.Basket.Api/Dockerfile

volumes:
  postgres.catalog:
  postgres.basket:

